Repository kucc/KUCheckCheck, pull requests merged in 2022-02, with the labels that each got.

#91 LoginPage 반응형으로 제작
  src/pages/LoginPage/LoginForm/style.js
  src/pages/LoginPage/index.jsx
  src/pages/LoginPage/style.js
Labels: enhancement, Refactoring

#92 JoinPage 반응형으로 제작
  src/pages/JoinPage/JoinForm/style.js
  src/pages/JoinPage/index.jsx
  src/pages/JoinPage/style.js
Labels: enhancement, Refactoring

#93 모바일 사이즈로 인해 텍스트 워딩 수정
  src/pages/JoinPage/JoinForm/index.jsx
Labels: petty issue

#94 MainTopContainer 추가 수정
  src/pages/MainPage/MainTopContainer/MMainTopContainer.jsx
  src/pages/MainPage/MainTopContainer/PMainTopContainer.jsx
  src/pages/MainPage/MainTopContainer/style.js
Labels: Refactoring

#95 MainPage 세션수강인원, 등록하기 기능 제외 반응형 적용
  src/components/CourseContainer/index.jsx
  src/components/CourseContainer/style.js
  src/pages/MainPage/MainBottomContainer/MMainBottomContainer.jsx
  src/pages/MainPage/MainBottomContainer/PMainBottomContainer.jsx
  src/pages/MainPage/MainBottomContainer/index.js
  src/pages/MainPage/MainBottomContainer/style.js
  src/pages/MainPage/MainSearch/index.jsx
  src/pages/MainPage/MainSearch/style.js
  src/pages/MainPage/index.jsx
  src/utility/COMMON_STYLE.js
Labels: enhancement, Refactoring

#99 courseAttendance 페이지 반응형 추가
  src/App.js
  src/components/Buttons/FullWidthButton/index.jsx
  src/components/Buttons/FullWidthButton/style.js
  src/components/UserCard/style.js
  src/pages/AttendancePage/CourseAttendanceCard/MCourseAttendanceCard.jsx
  src/pages/AttendancePage/CourseAttendanceCard/PCourseAttendanceCard.jsx
  src/pages/AttendancePage/CourseAttendanceCard/index.jsx
  src/pages/AttendancePage/CourseAttendanceCard/style.js
  src/pages/AttendancePage/CourseAttendanceTop/index.jsx
  src/pages/AttendancePage/CourseAttendanceTop/style.js
  src/pages/AttendancePage/index.jsx
  src/pages/AttendancePage/style.js
  src/pages/CoursePage/CourseBottom/CourseTimeTable/index.jsx
  src/utility/CONSTANTS.js
Labels: enhancement
